"""initial schema

Revision ID: 3f5636cb793d
Revises: 
Create Date: 2026-07-30 18:05:39.212919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5636cb793d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('midi_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('engine_versions', sa.String(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('time_signature', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chord_loops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('occurrences', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('chord', sa.String(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_chord_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('section_label', sa.String(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('roman_progression', sa.String(), nullable=False),
    sa.Column('repeats_of', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    op.drop_table('section_chord_summaries')
    op.drop_table('moods')
    op.drop_table('chords')
    op.drop_table('chord_loops')
    op.drop_table('analyses')
    op.drop_table('tracks')
    # ### end Alembic commands ###
